Oni\UserManagerBundle\Entity\Group:
    type: entity
    table: oni_user_groups
    repositoryClass: Oni\UserManagerBundle\Entity\GroupsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        roles:
            type: array
    lifecycleCallbacks: {  }
