Cms\UserManagerBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: Cms\UserManagerBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
        password:
            type: string
        plainPassword:
            type: string
        email:
            type: string
        salt:
            type: string
        roles:
            type: array
        active:
            type: integer
            options:
                default: 0
        enabled:
            type: integer
            options:
                default:0
        expired:
            type: integer
            options:
                default: 0
        expiresAt:
            type: integer
        credentialsExpired:
            type: integer
        credentialsExpireAt:
            type: integer
        lastLogin:
            type: datetime
            nullable: TRUE
        loggedInn:
            type: integer
            options:
                default: 0
        created:
            type: datetime
            nullable: TRUE
        modified:
            type: time
            nullable: TRUE
        modifiedBy:
            type: integer
            nullable: TRUE
    lifecycleCallbacks: {  }
