Oni\UserManagerBundle\Entity\User:
    type: entity
    table: oni_users
    repositoryClass: Oni\UserManagerBundle\Entity\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
        password:
            type: string
        plainPassword:
            type: string
        email:
            type: string
        salt:
            type: string
        roles:
            type: array
        active:
            type: integer
            options:
                default: 0
        active:
            type: integer
            options:
                default: 0
        enabled:
            type: integer
            options:
                default: 0
        expired:
            type: integer
            options:
                default: 0
        expiresAt:
            type: datetime
        credentialsExpired:
            type: integer
        credentialsExpireAt:
            type: datetime
        lastLogin:
            type: datetime
            nullable: TRUE
        loggedInn:
            type: integer
            options:
                default: 0
        created:
            type: datetime
            nullable: TRUE
            gedmo:
              timestampable:
                on: create
        modified:
            type: datetime
            nullable: TRUE
            gedmo:
              timestampable:
                on: update
        modifiedBy:
            type: integer
            nullable: TRUE
    lifecycleCallbacks: {  }
