cms_home:
    pattern:  /dashboard
    defaults: { _controller: UserManagerBundle:Dashboard:index }
cms_home2:
    pattern:  /
    defaults: { _controller: UserManagerBundle:Dashboard:index }
cms_login:
    path:      /login
    defaults:  { _controller: UserManagerBundle:Security:login}
