cms_login:
    path:      /admin/login
    defaults:  { _controller: UserManagerBundle:Security:login}
cms_login_check:
    path:      /admin/login_check
    defaults:  { _controller: UserManagerBundle:Security:check}
cms_login_out:
    path:      /admin/logout
    defaults:  { _controller: UserManagerBundle:Security:logout}
