parameters:


services:
    oni_user_entity:
        class: Oni\UserManagerBundle\Entity\User
    oni_user_provider:
        class: Oni\UserManagerBundle\Security\Authentication\Provider\UserProvider
        arguments: ["@oni_user_repository" , "@doctrine.orm.entity_manager"]
    oni_user_repository:
        class: Oni\UserManagerBundle\Entity\Repository\UserRepository
        factory: [ '@doctrine.orm.default_entity_manager',  getRepository]
        arguments:
                - Oni\UserManagerBundle\Entity\User
    oni_login_authenticator:
        class:     Oni\UserManagerBundle\Security\LoginAuthenticator
        arguments: ["@security.encoder_factory", "@doctrine.orm.entity_manager","@service_container"]
    oni_user.security.authentication.provider:
        class: Oni\UserManagerBundle\Security\Authentication\Provider\AuthenticationProvider
        arguments:
            - '' # User Provider
            - '@security.user_checker'
            - '' # Provider-shared Key
            - '@security.encoder_factory'
        public: false
    oni_user_event_subscriber:
        class: Oni\UserManagerBundle\EventListeners\UserEventSubscriber
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
           - { name: kernel.event_subscriber }

#    user.security.authentication.listener:
#        class: AppBundle\Security\Firewall\WsseListener
#        arguments: ['@security.token_storage', '@security.authentication.manager']
#        public: false
