parameters:
    user_provider: Cms\UserManagerBundle\Security\Authentication\Provider\UserProvider
    user_entity: Cms\UserManagerBundle\Entity\User
    user_entity_repository: Cms\UserManagerBundle\Entity\Repository\UserRepository
    user_factory: Cms\UserManagerBundle\Entity\Factory\UserFactory
    security_controller: Cms\ProductManagerBundle\Controller\IndexController

services:
    user:
        class: "%user_entity%"
    cms_user_provider:
        class: "%user_provider%"
        arguments: ["@user_repository" , "@doctrine.orm.entity_manager"]
    user_repository:
        class: "%user_entity_repository%"
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
                - "UserManagerBundle:User"
    login_authenticator:
        class:     Cms\UserManagerBundle\Security\LoginAuthenticator
        arguments: ["@security.encoder_factory", "@doctrine.orm.entity_manager"]
#    acme_user.password_resetting:
#        class: Acme\UserBundle\EventListener\PasswordResettingListener
#        arguments: [@router]
#        tags:
#            - { name: kernel.event_subscriber }
