<?php

namespace Oni\UserManagerBundle\Entity\Repository;

use Oni\CoreBundle\CoreBundle;
use Oni\CoreBundle\CoreGlobals;
use Oni\CoreBundle\Doctrine\Spec\Specification;
use Oni\CoreBundle\Doctrine\Specification\SpecificationInterface;
use Oni\ProductManagerBundle\ProductEvents;
use Doctrine\ORM\EntityRepository;


use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    private $table = CoreGlobals::USERS_ENTITY;


    function match(Specification $specification){

        $qb = $this->createQueryBuilder('u');
        $expr = $specification->match($qb, 'u');
        //var_dump($expr);exit;
        $query = $qb->where($expr)->getQuery();
        $specification->modifyQuery($query);
        return $query->getResult();
        
    }

}
