# Cms/UserManagerBundle/Resources/config/validation.yml
Oni\UserManagerBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 4
                max: 30
                minMessage: two.or.more.chars
                maxMessage: fifty.or.less.chars.
#        password:
#            - NotBlank: ~
#            - Length:
#                min: 6
#                max: 20
#                minMessage: six.or.more.chars
#                maxMessage: twenty.or.less.chars
        email:
            - Email: ~
        created:
            - Type: \DateTime
        modified:
            - Type: \DateTime
        lastLogin:
            - Type: \DateTime
        loggedInn:
            - Type:
                type: integer
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            errorPath: email
            message: email.already.in.use
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            errorPath: username
            message: username.already.in.use